#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '#######################################'
echo '# Pre Commit Check: Lint Commit Message' 
npx --no-install commitlint --edit "$1"
echo '# Finished'
echo '#######################################'
